import logging
from notion_client import Client
from config import settings

# Initialize Notion Client
# Global init removed, dynamic init in function

def create_notion_page(
    title: str, 
    blocks: list, 
    api_key: str = None, 
    database_id: str = None
):
    """
    Create a new page in the Notion database with structured blocks.

    Args:
        title: Page title
        blocks: List of Notion block objects (generated by Gemini)
        api_key: Notion API Key
        database_id: Notion Database ID
    """
    if not api_key or not database_id:
        return "Error: Notion API Key and Database ID are required."

    try:
        notion = Client(auth=api_key)
        # Create the page with Gemini-generated blocks
        notion.pages.create(
            parent={"database_id": database_id},
            properties={
                "Name": {"title": [{"text": {"content": title}}]},
            },
            children=blocks  # 直接使用 Gemini 生成的 Notion blocks
        )
        return "Success: Page created in Notion!"
    except Exception as e:
        logging.error(f"Notion Error: {e}")
        return f"Error creating Notion page: {e}"
