import logging
from notion_client import Client
from config import settings

# Initialize Notion Client
notion = Client(auth=settings.NOTION_API_KEY) if settings.NOTION_API_KEY else None

def create_notion_page(title: str, blocks: list):
    """
    Create a new page in the Notion database with structured blocks.

    Args:
        title: Page title
        blocks: List of Notion block objects (generated by Gemini)
    """
    if not notion or not settings.NOTION_DATABASE_ID:
        return "Error: Notion credentials not found."

    try:
        # Create the page with Gemini-generated blocks
        notion.pages.create(
            parent={"database_id": settings.NOTION_DATABASE_ID},
            properties={
                "Name": {"title": [{"text": {"content": title}}]},
            },
            children=blocks  # 直接使用 Gemini 生成的 Notion blocks
        )
        return "Success: Page created in Notion!"
    except Exception as e:
        logging.error(f"Notion Error: {e}")
        return f"Error creating Notion page: {e}"
